services:
  web:
    build: . #現在のディレクトリのDockerfileを指定
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/my_sommelier
    ports:
      - "8080:8080"
    depends_on: #先にdbから起動させる
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:16
    volumes:
      - db-store:/var/lib/postgresql/data # データを永続化するための設定
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    restart: always
volumes:
  db-store: